### ISSUE TITLE
tutorial failed: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by harryfyx** [JohnSnowLabs/johnsnowlabs#131]
I tried to follow the tutorial

https://nlu.johnsnowlabs.com/docs/en/install

stack trace
```Py
>>> from johnsnowlabs import nlp;print(nlp.load('emotion').predict('Wow that easy!'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harryfyx/code/scraper-tutorial/venv/lib/python3.8/site-packages/johnsnowlabs/__init__.py", line 2, in <module>
    from johnsnowlabs import nlp, settings, viz, lab
  File "/home/harryfyx/code/scraper-tutorial/venv/lib/python3.8/site-packages/johnsnowlabs/nlp.py", line 1, in <module>
    from .auto_install.health_checks.report import (
  File "/home/harryfyx/code/scraper-tutorial/venv/lib/python3.8/site-packages/johnsnowlabs/auto_install/health_checks/report.py", line 5, in <module>
    from johnsnowlabs import settings
  File "/home/harryfyx/code/scraper-tutorial/venv/lib/python3.8/site-packages/johnsnowlabs/settings.py", line 4, in <module>
    from johnsnowlabs.utils.env_utils import (
  File "/home/harryfyx/code/scraper-tutorial/venv/lib/python3.8/site-packages/johnsnowlabs/utils/env_utils.py", line 10, in <module>
    def inject_modules(imports: list[str], g):
TypeError: 'type' object is not subscriptable
```

It seems that the code wants to use `list` as type hint. But shouldn't that be something like `from typing import List; List[str]`?

Python version: Python 3.8.10
Module version: johnsnowlabs==4.4.2

**Comment by marait123** [comment]
I am facing the same issue

**Comment by pabla** [comment]
As a workaround, you could use Python 3.9.

**Comment by C-K-Loan** [comment]
Thanks for the report @harryfyx  this has been resolved in the latest release
